### ISSUE TITLE
Pen Tracking not working when dragging

### ISSUE THREAD

**Issue by tc324** [minttuNB/ppcat#1]
When dragging on the tablet, the pen tracking function does not work anymore. It just gets stuck on the position it currently is at until I lift my pen again. Hovering works fine, but I don't play like this unfortunately.    

OS: Windows 10 64Bit(started .exe in Win8 Compatibility Mode)
Tablet: Wacom CTL 480
Drivers: TabletDriverGUI 0.1.0 (reddit drivers)

I could deactivate the tapping function (tap = mouse click), but I usually navigate my game with the pen.

**Comment by minttuNB** [comment]
https://github.com/minttuNB/ppcat/commit/decc0c31118ebf89052e438b841323c53120b543
@tc324 This seems to have done the trick for me. Can you replace the file manually and confirm if it works?

**Comment by tc324** [comment]
@minttuNB thanks, that commit fixed the issue for me as well.

**Comment by Acclaiming** [comment]
@minttuNB not working for me (I'm using Wacom drivers 6.3.9w5)
