### ISSUE TITLE
Make it work on window 7

### ISSUE THREAD

**Issue by roxtigger2003** [minttuNB/ppcat#11]
![untitled](https://user-images.githubusercontent.com/36947924/45927199-91911880-bf59-11e8-8719-5ac72f76c40d.png)

**Comment by minttuNB** [comment]
Can you describe what your problem is?

**Comment by roxtigger2003** [comment]
it is overwritten by another window

**Comment by minttuNB** [comment]
Can you try turning Windows Aero on and checking if it works then?  
Also make sure you're using Window Capture and not Screen Capture.

**Comment by roxtigger2003** [comment]
I have enabled the aero window and used window capture

**Comment by minttuNB** [comment]
It looks like a problem with OBS, not the ppcat itself then.

**Comment by minttuNB** [comment]
Also, your OBS version seems to be a bit behind the latest (22.0.2), maybe updating it could help?

**Comment by roxtigger2003** [comment]
I tried all the versions but still failed

**Comment by roxtigger2003** [comment]
Did you edit it?

**Comment by minttuNB** [comment]
Edit what?  
I don't think I can help you with this issue to be honest, it really seems to be on your end - I tried on several Windows 7 computers and didn't encounter this bug at all.

**Comment by minttuNB** [comment]
Can you tell me what it was?  
Might be helpful for future reference.
