### ISSUE TITLE
displaying issue

### ISSUE THREAD

**Issue by mouzee1337** [minttuNB/ppcat#3]
well im using windows 10 and enabled the compatibility mode (windows 8) and what i see is basically this:
https://puu.sh/BwIq2/117eaa4fcb.png
i reinstalled it, launched it as admin and disabled the compatibility mode and it looks like the same issue is still there even without the compatibility mode. 
send help ¯\_(ツ)_/¯

**Comment by unalatadefrijoles** [comment]
same to me,

**Comment by minttuNB** [comment]
@mouzee1337 @unalatadefrijoles Please do try whether the new version fixes this or not.  
I think it is related to the now-removed waving animation, but I need you to confirm.

**Comment by mouzee1337** [comment]
@minttuNB the new version fixed the problem, everything works now.
