### ISSUE TITLE
Issues when osu! is on fullscreen mode

### ISSUE THREAD

**Issue by Iryya** [minttuNB/ppcat#4]
ppcat only works when osu! is not on fullscreen (it works when osu! is on borderless fullscreen, but you get a lot of input lag in osu!)

**Comment by minttuNB** [comment]
In case you minimize the ppcat window, it's known to stop animating.  
You can test if the new ppcat version fixes it for you, as it's a little less resource-heavy.  
Also, what system and gfx card are you using?

**Comment by Iryya** [comment]
I'm running an AMD Radeon HD 7790 1GB, i5 3570k, 16GB of RAM. I don't have any issues related to lag when I have pp cat and osu open at the same time. ppcat just stops moving when I tab into osu!. As soon as I tab out from osu, it works just fine. 

Maybe people are not having issues because their osu! is running with Fullscreen Optimizations enabled (you can check osu!.exe under the compatibility tab to see if they are enabled on Windows 10) which forces the app to always go fullscreen borderless. Like I said, switching the in game settings on osu to fullscreen borderless solves this issue.

**Comment by minttuNB** [comment]
I'll have to check if I have Fullscreen optimizations enabled myself. My setup is far worse than yours but I get 0.34ms with uncapped fps (and the cat works). Thanks for the followup

**Comment by minttuNB** [comment]
![image](https://user-images.githubusercontent.com/22272913/45757449-5abbb980-bc5e-11e8-9c20-711bb828d906.png)  
Looks like I don't even have an option for that.

**Comment by minttuNB** [comment]
@Iryya fixed in https://github.com/minttuNB/ppcat/commit/6eca42e8490a41ccf6d970af56c746fbc6bcda8a ,  
you can replace the file manually for now :)
