### ISSUE TITLE
Implement letterbox support

### ISSUE THREAD

**Issue by ConspiracyPizza** [minttuNB/ppcat#5]
Since osu maps are in 4:3 ratio, I would like to be able to set the resolution of ppcat to about 1280x960 for a 1920x1080 screen to achieve maximum pen movement, however, currently I think that changing resolution just sets the screen resolution from the top left, so I was wondering if there was a way to set pp cat to set resolution from the middle of the screen somehow. Thanks.

**Comment by minttuNB** [comment]
Implemented in https://github.com/minttuNB/ppcat/commit/f126525a3b498c04acdeb9747258018975f78f41 , will be added in the 1.1.0 release.
