### ISSUE TITLE
Streamlabs OBS Support

### ISSUE THREAD

**Issue by Psypherical** [minttuNB/ppcat#7]
When trying to create a Display or Game Capture of the `ppcat.exe` window on Streamlabs OBS 0.9.8, the widget comes up black, but the cursor can be seen. I am using ppcat version 1.1.0 and I have Windows 10 build 1803.
>https://gyazo.com/ccb47236c53bf520ce7d410dbbb0f500

Is there any way to fix this, or is there a fix on the way?

**Comment by minttuNB** [comment]
I'm gonna download Streamlabs OBS today and do some testing (I usually use the regular OBS).  
Do you still have a black screen ppcat if you use Screen Capture instead? If you don't, this might be OBS' problem.

**Comment by Zpinxer** [comment]
Are you sure you have comatibility setting on Windows 8?

**Comment by minttuNB** [comment]
![image](https://user-images.githubusercontent.com/22272913/45758165-f0a41400-bc5f-11e8-8db3-a7a9b2bd5839.png)
This is after setting this on the ppcat.exe in Streamlabs OBS.  
![image](https://user-images.githubusercontent.com/22272913/45758194-06b1d480-bc60-11e8-8d88-5a7e4cf424b3.png)  
I, too, did have a black screen without changing that setting. From what I know, the black screen without Win8 compatibility setting is a known issue with both the regular OBS and Streamlabs OBS when running Electron apps.

**Comment by Psypherical** [comment]
THANK YOU SO MUCH HOLEE
